linecommand/urls.py
from django.conf.urls import patterns, include, url
from linecommand import views
from data import *

urlpatterns = patterns('',
                       # Examples:
                       # Index
                       url(r'^$', views.Index, name='index'),
                       # Paypal
                       url(r'^(?P<client_id>\d+)/paypal/$', views.paypal, name='paypal'),
                       url(r'^(?P<client_id>\d+)/paypal/success/$', views.paypal_success, name='paypal_success'),
                       # Client Lists
                       url(r'^list/', views.ClientList, name='client_list'),
                       # Creat Client
                       url(r'^create/$', views.Create, name='createclient'),
                       # Import numbers
                       url(r'^import/$', views.NumbersImport, name='import_numbers'),
                       # Deposit
                       url(r'^(?P<client_id>\d+)/deposit/$', views.Deposit, name='deposit'),
                       # Modify Client
                       url(r'^(?P<client_id>\d+)/modify/$', views.SetPrice, name='modify'),
                       # Buy Numbers
                       url(r'^(?P<client_id>\d+)/numbers/$', views.PurchaseNumbers, name='numbers'),
                       url(r'^(?P<client_id>\d+)/displaynum/$', views.ShowNumbers, name='shownumbers'),
                       #url(r'^(?P<client_id>\d+)/details/$', views.Details, name='detail'),
                       # Client dashboard
                       url(r'^(?P<client_id>\d+)/details/$', views.Client_main, name='client_main'),
                       # Client buy numbers
                       url(r'^(?P<client_id>\d+)/details/buyNumbers/$', views.Client_buyNumbers, name='client_numbers'),
                       url(r'^(?P<client_id>\d+)/details/createClient/$', views.Client_createClient,
                           name='client_create'),
                       url(r'^(?P<client_id>\d+)/details/exportNumbers/$', views.Client_exportNumbers,
                           name='export_numbers'),
                       url(r'^(?P<client_id>\d+)/details/referalLink/$', views.Client_Referal,
                           name='client_referal'),
                       url(r'^(?P<client_id>\d+)/details/randNumbers/$', views.Client_randomNumbers,
                           name='client_randnumbers'),
                       url(r'^(?P<client_id>\d+)/details/geoNumbers/$', views.Client_GeoNumbers,
                           name='client_geonumbers'),
                       url(r'^(?P<client_id>\d+)/details/tempNumbers/$', views.Client_NonclNumbers,
                           name='client_buynoncl'),
                       # Client SMS Management
                       url(r'^(?P<client_id>\d+)/details/smsManagement/$', views.Client_sms_management,
                           name='client_sms'),
                       # Maintenance
                       # url(r'^(?P<client_id>\d+)/details/geoNumbers/$', views.Maintenance, name='client_geonumbers'),
                       # acc history
                       # Client History
                       url(r'^(?P<client_id>\d+)/details/accHistory/$', views.Client_History, name='client_history'),
                       # Client Fundings
                       url(r'^(?P<client_id>\d+)/details/fundings/$', views.Client_Funding, name='client_funding'),
                       # Support
                       url(r'^(?P<client_id>\d+)/details/support/$', views.VideoTutorial, name='video_tutorial'),
                       # Call Reporting
                       url(r'^(?P<client_id>\d+)/details/call_reporting/$', views.client_cdr, name='cdr'),
                       url(r'^(?P<client_id>\d+)/details/call_reporting/(?P<num>\d+)$',
                           views.client_cdr_detail, name='cdr_detail'
                       ),
                       # Settings
                       url(r'^(?P<client_id>\d+)/details/settings/$', views.Client_Settings, name='client_settings'),
                       #url(r'^(?P<client_id>\d+)/details/editHtml/$', views.Client_editCode, name='client_editCode'),
                       # Area Codes
                       url(r'^(?P<state>\w+)/areacodes/$', views.AreaCodes, name='load_areacodes'),
                       # Login / Logout
                       url(r'^login/', 'django.contrib.auth.views.login', {'template_name': 'linecommand/login.html'}),
                       url(r'^logout/$', 'django.contrib.auth.views.logout', {'next_page': '/login/'}, name='logout'),
                       # Sign Up
                       url(r'^signup/$', views.SignUp, name='signup'),
                       url(r'^signup/(?P<uidb36>[0-9A-Za-z]+)/$', views.ReferalSignUp, name='referal_signup'),
                       # Password reset
                       url(r'^password/reset/$', 'django.contrib.auth.views.password_reset',
                           {'post_reset_redirect': 'password_reset_done',
                            'template_name': 'linecommand/password_reset_form.html',
                            'email_template_name': 'linecommand/password_reset_email.html'},
                           name='password_reset'),
                       url(r'^password/reset/done/$', 'django.contrib.auth.views.password_reset_done',
                           {'template_name': 'linecommand/password_reset_done.html'},
                           name='password_reset_done'),
                       url(r'^password/reset/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$',
                           'django.contrib.auth.views.password_reset_confirm',
                           {'post_reset_redirect': 'password_reset_complete',
                            'template_name': 'linecommand/password_reset_confirm.html'},
                           name='password_reset_confirm'),
                       url(r'^password/done/$', 'django.contrib.auth.views.password_reset_complete',
                           {'template_name': 'linecommand/password_reset_complete.html'},
                           name='password_reset_complete')
)

urlpatterns += patterns('',
    url(r'^something/hard/to/guess/', include('paypal.standard.ipn.urls')),
    url(r'^985e12aa-db0f-4b83-88fd-8edd1717404e/$', views.showstats, name='export_stats'),
)

urlpatterns += patterns('',
    url(r'^api/v1.0/geo/Orders/$', Orders.as_view(), name='Orders')
)

linecommand/forms.py
from django import forms
from django.contrib.auth.models import User
from django.core.validators import validate_email
from django.core.exceptions import ValidationError
from linecommand.models import Clients, UserHtml
from django.db.models import Sum
import hashlib


class SignUpForm(forms.Form):
    email = forms.EmailField(required=True, label='*Email', help_text='Your e-mail address',
                             widget=forms.TextInput(attrs={'placeholder': 'Your E-mail Address'}))
    password = forms.CharField(min_length=6, label='*Password', widget=forms.PasswordInput)
    name = forms.CharField(required=True, widget=forms.TextInput(attrs={'placeholder': 'Full Name'}))
    billing_address = forms.CharField(widget=forms.Textarea, label='Billing Address', required=False)
    skype_id = forms.CharField(label='Skype ID', required=False,
                               widget=forms.TextInput(attrs={'placeholder': 'Your skype ID'}))
    aol_id = forms.CharField(label='AOL ID', required=False,
                             widget=forms.TextInput(attrs={'placeholder': 'Your AOL ID'}))
    phone = forms.CharField(required=False,
                            widget=forms.TextInput(attrs={'placeholder': 'Your Contact Number'}))


class ReferalSignUpForm(SignUpForm):
    def save(self, client=Clients.objects.get(pk=1), commit=True):
        username = hashlib.md5(self.cleaned_data['email']).hexdigest()[2:]
        new_user = User.objects.create_user(
            username=username,
            email=self.cleaned_data['email'],
            password=self.cleaned_data['password']
        )
        new_user.save()
        new_client = Clients.objects.create(
            name=self.cleaned_data['name'],
            address=self.cleaned_data['billing_address'],
            skype=self.cleaned_data['skype_id'],
            aol_id=self.cleaned_data['aol_id'],
            phone=self.cleaned_data['phone'],
            binded=0,
            user=new_user,
            parent=client
        )
        new_client.save()
        return new_client


class CreateClient(forms.Form):
    email = forms.EmailField(required=True, label='*Email', help_text='Your e-mail address',
                             widget=forms.TextInput(attrs={'placeholder': 'Your E-mail Address'}))
    password = forms.CharField(min_length=6, label='*Password', widget=forms.PasswordInput)
    skype = forms.CharField(required=False, widget=forms.TextInput(attrs={'placeholder': 'Your Skype ID'}))
    phone = forms.CharField(required=False, widget=forms.TextInput(attrs={'placeholder': 'Your Contact Number'}))
    active = forms.BooleanField(label="*Active", required=True)
    price_30 = forms.FloatField(required=True, label="*Price for 30 days Random number", widget=False)
    price_60 = forms.FloatField(required=True, label="*Price for 60 days Random number", widget=False)
    price_90 = forms.FloatField(required=True, label="*Price for 90 days Random number", widget=False)
    geo30_price = forms.FloatField(required=True, label="*Price for 30 days Geo number", widget=False)
    geo90_price = forms.FloatField(required=True, label="*Price for 90 days Geo number", widget=False)
    noncl_price = forms.FloatField(required=True, label="*Price for 7 day temporary number", widget=False)
    discount = forms.FloatField(required=True, label="*Percentage discount on renewals",
                                min_value=0.0, max_value=100.0,
                                widget=forms.TextInput(attrs={'placeholder': '% value from 0.0 to 100.0'}))

    class Meta:
    #    model = Clients
        fields = ['email', 'password', 'skype', 'phone', 'price_30', 'price_60', 'price_90', 'active']
        #    widgets = {
        #               'password': forms.PasswordInput(),
        #              }


class DepositForm(forms.Form):
    # client = forms.ChoiceField(widget=forms.Select(attrs={'style':'width:220px'}), label="Client")
    client = forms.IntegerField(widget=forms.HiddenInput(attrs={'readonly': 'readonly'}))
    current_amount = forms.CharField(widget=forms.TextInput(attrs={'readonly': 'readonly'}), label="Current Balance")
    amount = forms.FloatField(required=True, label="*Specify Amount", widget=False)

    def __init__(self, children_list, *args, **kwargs):
        super(DepositForm, self).__init__(*args, **kwargs)
        # self.fields['client'].choices = [(int(obj.id), str(obj.user)) for obj in children_list]
        self.fields['client'].initial = children_list[0].id
        initial_amount = children_list.annotate(total=Sum('account__amount'))[0].total
        if not initial_amount:
            display_amount = 0.0
        else:
            display_amount = initial_amount
        self.fields['current_amount'].initial = display_amount

    class Meta:
        # model = Accounts
        fields = ['client', 'current_amount', 'amount']


class ChangePrice(forms.Form):
    client = forms.IntegerField(widget=forms.HiddenInput(attrs={'readonly': 'readonly'}))
    price_30 = forms.FloatField(required=True, label='*Price for 30 days random', widget=False)
    price_60 = forms.FloatField(required=True, label='*Price for 60 days random', widget=False)
    price_90 = forms.FloatField(required=True, label='*Price for 90 days random', widget=False)
    geo_30 = forms.FloatField(required=True, label='*Price for 30 days geo number', widget=False)
    geo_90 = forms.FloatField(required=True, label='*Price for 90 days geo number', widget=False)
    noncl_price = forms.FloatField(required=True, label="*Price for 7 day temporary number", widget=False)
    discount = forms.FloatField(required=True, min_value=0.0, max_value=100.0,
                                label="*Percentage discount on renewals",
                                widget=forms.TextInput(attrs={'placeholder': '% value from 0.0 to 100.0'}))

    class Meta:
        fields = ['client', 'price_30', 'price_60', 'price_90', 'geo_30', 'geo_90']


class AddNumbers(forms.Form):
    choice_forward = (('FORWARD', 'FORWARD'),
                      ('VOICEMAIL', 'VOICEMAIL'))
    choice_duration = ((90, '90 Days'),
                       (60, '60 Days'),
                       (30, '30 Days'))
    client = forms.IntegerField(widget=forms.HiddenInput(attrs={'readonly': 'readonly'}))
    count = forms.IntegerField(min_value=0, required=True, label="*Count (Number of lines to order)",
                               widget=forms.TextInput(attrs={'style': 'width:30px'}))
    forward = forms.ChoiceField(widget=forms.Select(attrs={'style': 'width:120px'}), choices=choice_forward)
    forward_data = forms.CharField(max_length=100, required=True, label="*Forward Data",
                                   widget=forms.TextInput(attrs={'placeholder': '202xxxxxxx or p@abc.com'}))
    duration = forms.ChoiceField(widget=forms.Select(attrs={'style': 'width:95px'}), choices=choice_duration)
    notes = forms.CharField(max_length=128, required=False, label='Note',
                            widget=forms.TextInput(attrs={'placeholder': 'Enter a note for purchase.'}))

    def __init__(self, children_list, *args, **kwargs):
        super(AddNumbers, self).__init__(*args, **kwargs)
        self.fields['client'].initial = children_list[0].id

    class Meta:
        fields = ['count', 'forward', 'forward_data', 'duration']


class BalanceForm(forms.Form):
    client = forms.IntegerField(widget=forms.HiddenInput(attrs={'readonly': 'readonly'}))
    amount = forms.FloatField(required=True, label="*Specify Amount", widget=False)

    def __init__(self, children_list, *args, **kwargs):
        super(BalanceForm, self).__init__(*args, **kwargs)
        self.fields['client'].initial = children_list[0].id

    class Meta:
        # model = Accounts
        fields = ['client', 'amount']


class UpdateNumbersForm(forms.Form):
    choice_forward = (('FORWARD', 'FORWARD'),
                      ('VOICEMAIL', 'VOICEMAIL'))
    forward = forms.ChoiceField(widget=forms.Select(attrs={'style': 'width:120px'}), choices=choice_forward)
    forward_data = forms.CharField(max_length=100, required=True, label="*Forward Data",
                                   widget=forms.TextInput(attrs={'placeholder': '202xxxxxxx or p@abc.com'}))

    class Meta:
        fields = ['forward', 'forward_data']


class UpdateSMSTypeForm(forms.Form):
    choice_sms_type = (('EMAIL', 'Email'),
                      ('WEB_REQUEST', 'Web Request'),
                       ('FORWARD', 'Forward'))
    sms_type = forms.ChoiceField(widget=forms.Select(attrs={'style': 'width:120px'}), choices=choice_sms_type)
    sms_data = forms.CharField(max_length=100, required=True, label="*SMS Data",
                               widget=forms.TextInput())

    class Meta:
        fields = ['forward', 'forward_data']


class RenewNumbersForm(forms.Form):
    choice_duration = ((90, '90 Days'),
                       (60, '60 Days'),
                       (30, '30 Days'))
    duration = forms.ChoiceField(widget=forms.Select(attrs={'style': 'width:95px'}), choices=choice_duration)

    class Meta:
        fields = ['duration']


class ChangeUserForm(forms.Form):
    old_username = forms.CharField(required=True, label="Old Email")
    new_username = forms.EmailField(required=True, label="New Email")

    class Meta:
        fields = ['old_username', 'new_username']


class ChangePasswordForm(forms.Form):
    old_password = forms.CharField(required=True, label="Old Password", widget=forms.PasswordInput)
    new_password = forms.CharField(required=True, label="New Password", widget=forms.PasswordInput)

    class Meta:
        fields = ['old_password', 'new_password']


class ExportNumbers(forms.Form):
    choice_export = (('0', "Today's"),
                     ('1', 'AllNumbers'),
                     ('2', 'Selected'))
    export = forms.ChoiceField(widget=forms.Select(attrs={'style': 'width:120px'}), choices=choice_export)

    class Meta:
        fields = ['export']


class RandomNumbersForm(forms.Form):

linecommand/templates/linecommand/client_createclient.html
{% extends "linecommand/base2.html" %}

{% comment %}
{% block navbar %}
  <ul class="nav nav-pills">
    <li><a href="{% url 'client_main' client.id %}">Dashboard</a></li>
    {# <li><a href="#addbalance">Add Balance</a></li> #}
    <li><a href="{% url 'client_numbers' client.id %}">Buy Numbers</a></li>
    <li class="active"><a href="#createclient">Create Client</a></li>
    <li><a href="{% url 'client_editCode' client.id %}">Edit HTML</a></li>
  </ul>
{% endblock %}
{% endcomment %}

{% block create %}
  <li class="active"><a href="#createclient">Create Client</a></li>
{% endblock %}

{% block section %}
  <section id="createclient" style="margin-top:-25px;">
    <div class="page-header">
      <h3>Create Client</h3>
    </div>
    {% if create_error %}
    <div class="row-fluid">
      <div class="span4 offset1">
        <div class="alert alert-dismissable alert-warning">
          {{ create_error }}
        </div>
      </div>
    </div>
    {% endif %}
    <div class="row-fluid">
      <div class="span9 offset1 well well-small">
        <form class="form-horizontal" action="{% url 'client_create' client.id %}" method="post">{% csrf_token %}
          {% for field in client_form.hidden_fields %}
            {{ field }}
          {% endfor %}
          {% for field in client_form.visible_fields %}
            <div class="control-group{% if field.errors %} error{% endif %}">
              <label class="control-label"><strong>{{ field.label }}</strong></label>
              <div class="controls">
                {{ field }}
                <span class="help-inline">{{ field.errors }}</span>
              </div>
            </div>
          {% endfor %}
          <div class="control-group">
            <div class="controls">
              <input class="btn btn-primary btn-small fa-input" type="submit" onclick="this.disabled=true,this.form.submit();" name="create_client" 
value="Create" />
              <input type="hidden" name="next" value="{{ next }}" />
            </div>
          </div>
        </form>
      </div>
    </div>
  </section>
{% endblock %}

linecommand/templates/linecommand/client_list.html
{% for node in master.get_children.order_by %}
    {% include "linecommand/treeview.html" %}
{% endfor %}

linecommand/templates/linecommand/client_nonclnumbers.html
{% extends "linecommand/base2.html" %}
{% load static %}

{% block css %}
    <link href="{% static 'linecommand/css/page-load.css' %}" rel="stylesheet">
{% endblock %}

{% block head %}
    <script type="text/javascript">
        $(document).ready(function () {
            $("#loading-div-background").css({ opacity: 1.0 });
        });

        function ShowProgressAnimation() {
            $("#loading-div-background").show();
        }
    </script>
{% endblock %}

{% block buynums %}active{% endblock %}

{% block section %}
    <section id="buynumbers" style="margin-top:-25px;">
        <div class="page-header">
            <h3>Purchase Temporary 7-Day Numbers</h3>
        </div>
        {% if numbers_errors %}
            <div class="row-fluid">
                <div class="span4 offset1">
                    <div class="alert alert-dismissable alert-error">
                    <ul>
                        {% for err in numbers_errors %}
                            <li>{{ err }}</li>
                        {% endfor %}
                    </ul>
                    </div>
                </div>
            </div>
        {% endif %}
        <div class="row-fluid">
            <div class="span9 offset1 well well-small" style="padding:0 0 0 20px;">
                <h5><strong>Current Balance</strong> &#36;{% if balance == None %}0.00{% else %}
                    {{ balance|floatformat:2 }}{% endif %}</h5>
                <h5>Numbers Associated are {{ numbers|length }}</h5>
                <h5><b>Buy Numbers for</b></h5>
                {% with buy=True template_name="linecommand/showprice.html" %}
                    {% include template_name %}
                {% endwith %}
            </div>
        </div>

        <div class="row-fluid">
            <div class="span9 offset1 well well-small">
                <form class="form-horizontal" action="{% url 'client_buynoncl' client.id %}"
                      method="post">{% csrf_token %}
                    {% for field in number_form.hidden_fields %}
                        {{ field }}
                    {% endfor %}
                    {% for field in number_form.visible_fields %}
                        <div class="control-group{% if field.errors %} error{% endif %}">
                            <label class="control-label"><strong>{{ field.label }}</strong></label>

                            <div class="controls">
                                {{ field }}
                                <span id="{{ field.auto_id }}_err" class="help-inline">{{ field.errors }}</span>
                            </div>
                        </div>
                    {% endfor %}
                    <div class="control-group">
                        <div class="controls">
{#                            <input class="btn btn-primary btn-small fa-input" type="submit"#}
{#                                   onclick="this.disabled=true,this.form.submit();" name="buy_numbers" value="Submit"/>#}
                            <input class="btn btn-primary btn-small fa-input" type="submit"
                                   onclick="ShowProgressAnimation();" name="buy_numbers" value="Submit"/>
                            <input type="hidden" name="next" value="{{ next }}"/>
                        </div>
                    </div>
                </form>
                <div id="loading-div-background">
                    <div id="loading-div" class="ui-corner-all">
                        <img src="{% static 'linecommand/images/bars.gif' %}" alt="Loading.."/>
                    </div>
                </div>
            </div>
        </div>
    </section>
{% endblock %}

{% block scripting %}
    <script type="text/javascript">
        $(document).ready(function () {
            //called when key is pressed in textbox
            $("#id_forward_data").keypress(function (e) {
                //if the letter is not digit then display error and don't type anything
                var drp = $("#id_forward").val();
                if (drp === "FORWARD") {
                    if (e.which != 8 && e.which != 0 && (e.which < 48 || e.which > 57)) {
                        //display error message
                        $("#id_forward_data_err").html("Only Digits allowed for forward").show().fadeOut(1500);
                        return false;
                    }
                }
{#                else {#}
{#                    $(this).prop('type', 'email');#}
{#                    return true;#}
{#                }#}
            });
        });
    </script>
{% endblock %}

linecommand/templates/linecommand/funding_email.html
{% load i18n %}
{% load url from future %}

{% autoescape off %}

    {% blocktrans %}
        You're receiving this e-mail because your client {{ client }}
        account has been deposited with amount ${{ amount }}.
    {% endblocktrans %}

    {% blocktrans %}The {{ site_name }} team{% endblocktrans %}

{% endautoescape %}

linecommand/templates/linecommand/navbar.html
<ul class="nav nav-pills">
    {% block dashboard %}
        <li><a href="{% url 'client_main' client.id %}">Dashboard</a></li>{% endblock %}
    {% block buynums %}
        <li><a href="{% url 'client_numbers' client.id %}">Buy Numbers</a></li>{% endblock %}
    {% block create %}
        <li><a href="{% url 'client_create' client.id %}">Create Client</a></li>{% endblock %}
    {% block funding %}
        <li><a href="{% url 'paypal' client.id %}">Fund Account</a></li>{% endblock %}
    {% block settings %}
        <li><a href="{% url 'client_settings' client.id %}">Settings</a></li>{% endblock %}
    {% block edit %}
        <li><a href="{% url 'client_editCode' client.id %}">Edit HTML</a></li>{% endblock %}
</ul>

linecommand/templates/linecommand/password_reset_complete.html
{% extends "linecommand/reset_base.html" %}

{% block title %}Password reset complete{% endblock title %}

{% block section %}
<div class="page-header">
 <h3>Reset Complete</h3>
</div>
<div class="span9 offset1">
  <p>Your password has been set. 
   You may go ahead and log in now.</p>
  <a href="/login/">Log in</a>
</div>
{% endblock %}

linecommand/templates/linecommand/password_reset_confirm.html
{% extends "linecommand/reset_base.html" %}

{% block title %}Setting New password{% endblock title %}

{% block section %}
    <div class="page-header">
        <h3>Setting New Password</h3>
    </div>

    <div class="row-fluid">
    <div class="span9 offset1 well well-small">
    <form class="form-horizontal" action="" method="post">
        {% csrf_token %}
        {% if validlink %}
            <p>Please enter your new password twice.
                So we can verify you typed it in correctly.</p>
            {% for field in form.hidden_fields %}
                {{ field }}
            {% endfor %}
            {% for field in form.visible_fields %}
                <div class="control-group{% if field.errors %} error{% endif %}">
                    <label class="control-label"><strong>{{ field.label }}</strong></label>

                    <div class="controls">
                        {{ field }}
                        <span class="help-inline">{{ field.errors }}</span>
                    </div>
                </div>
            {% endfor %}
        {% else %}
            <h4>Password reset unsuccessful</h4>
            <p>The password reset link was invalid,
                possibly because it has already been used.
                Please request a new password reset.</p><br/>
        {% endif %}
        <div class="control-group{% if field.errors %} error{% endif %}">
                    <div class="controls">
                        <button type="submit" class="btn btn-primary btn-small">Change password</button>
                    </div>
                </div>

    </form>
{% endblock %}

linecommand/templates/linecommand/password_reset_email.html
{% load i18n %}
{% load url from future %}
{% autoescape off %}

    {% blocktrans %}
        You're receiving this e-mail because you requested
        a password reset for your user account at {{ site_name }}.
    {% endblocktrans %}

    {% trans "Please go to the following page and choose a new password:" %}

    {% block reset_link %}
        {{ protocol }}://{{ domain }}{% url 'password_reset_confirm' uidb64=uid token=token %}
    {% endblock %}

    {% trans "Your username, in case you've forgotten:" %} {{ user.email }}

    {% trans "Thanks for using our site!" %}

    {% blocktrans %}The {{ site_name }} team{% endblocktrans %}

{% endautoescape %}

linecommand/templates/linecommand/paypal.html
{% extends "linecommand/base2.html" %}
{% load static %}

{% block css %}
    <link href="{% static 'linecommand/css/page-load.css' %}" rel="stylesheet">
{% endblock %}

{% block head %}
<script type="text/javascript">
    function showProgress() {
            $("#loading-div-background").show();
    }
    function hideProgress() {
        $("#loading-div-background").hide();
    }
    function manualsubmit() {
        $("#form_fund").submit(function (event) {
            event.preventDefault();
            sendform();
            return false;
        });
    }
    function sendform () {
        showProgress();
        var frm = $('#form_fund');
        $.ajax({
            type: frm.attr('method'),
            url: frm.attr('action'),
            data: frm.serialize(),
            cache: false,
            success: function (data) {
                $("#paypal_div").html(data);
                manualsubmit();
            }
        });
        hideProgress();
    }
</script>
{% endblock %}

{% block funding %}
    <li class="active"><a href="#buy_credits">Fund Account</a></li>
{% endblock %}

{% block section %}
    <section id="buy_credits">
        <div class="page-header">
            <h3>Fund Account</h3>
        </div>
        <div class="row-fluid">
            {% if client.is_paypal_active %}
            <div id="paypal_div" class="span9 offset1 well well-small">
                {% include 'linecommand/paypal_form.html' %}
            </div>
            {% else %}
            <h5>Paypal is not enabled for you right now. Please contact your admin.</h5>
            {% endif %}
        </div>
        <div class="row-fluid">
            <div class="span9 offset1 well well-small" style="padding:0 0 0 20px;">
                <h5><b>Buy Numbers for</b></h5>
                {% with buy=False template_name="linecommand/showprice.html" %}
                    {% include template_name %}
                {% endwith %}
            </div>
        </div>
        <div id="loading-div-background">
            <div id="loading-div" class="ui-corner-all">
                <img src="{% static 'linecommand/images/bars.gif' %}" alt="Loading..."/>
            </div>
        </div>
    </section>
{% endblock %}

{% block scripting %}
<script type="text/javascript">
$(document).ready(function() {
    manualsubmit();
});
</script>
{% endblock %}

linecommand/templates/linecommand/showstats.html
<table class="table table-condensed" style="width:30%;margin-left:30px;">
    <thead>
    <th>Category</th>
    <th>Number Count</th>
    </thead>
    <tbody>
    {% for elem in stats %}
        {% if elem.duration == 30 or elem.duration == 60 or elem.duration == 90 %}
        <tr>
            <td>{{ elem.duration }} Days Random</td>
            <td>{{ elem.count }}</td>
        </tr>
        {% endif %}
    {% endfor %}
    </tbody>
</table>

linecommand/templates/linecommand/signup.html
{% extends "linecommand/base.html" %}
{% load static %}

{% block section %}
<section>
    <div class="page-header">
            <h3>Sign Up</h3>
    </div>
    <div class="row-fluid">
            <div class="span9 offset1">
                <form class="form-horizontal" action="{% if not referal %}{% url 'signup' %}{% endif %}" method="post">
                    {% csrf_token %}
                    {% for field in signUpForm.hidden_fields %}
                        {{ field }}
                    {% endfor %}
                    {% for field in signUpForm.visible_fields %}
                        <div class="control-group{% if field.errors %} error{% endif %}">
                            <label class="control-label"><strong>{{ field.label }}</strong></label>

                            <div class="controls">
                                {{ field }}
                                <span class="help-inline">{{ field.errors }}</span>
                            </div>
                        </div>
                    {% endfor %}
                    <div class="control-group">
                        <div class="controls">
                            <input class="btn btn-primary btn-small fa-input" type="submit"
                                   onclick="this.disabled=true,this.form.submit();" name="SignUp" value="SignUp"/>
                            <input type="hidden" name="next" value="{{ next }}"/>
                        </div>
                    </div>
                </form>
            </div>
        </div>
</section>
{% endblock %}